<?php

namespace Kotchasan;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-03-02 at 20:21:24.
 */
class ArrayToolTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var ArrayTool
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new ArrayTool();
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{

	}

	/**
	 * Generated from @assert (array(array('id' => 2, 'value' => 'two'), array('id' => 3, 'value' => 'three'), array('id' => 1, 'value' => 'one'))) [==] array(array('id' => 1, 'value' => 'one'), array('id' => 2, 'value' => 'two'), array('id' => 3, 'value' => 'three')).
	 *
	 * @covers Kotchasan\ArrayTool::sort
	 */
	public function testSort()
	{

		$this->assertEquals(
			array(array('id' => 1, 'value' => 'one'), array('id' => 2, 'value' => 'two'), array('id' => 3, 'value' => 'three')), \Kotchasan\ArrayTool::sort(array(array('id' => 2, 'value' => 'two'), array('id' => 3, 'value' => 'three'), array('id' => 1, 'value' => 'one')))
		);
	}

	/**
	 * Generated from @assert (array('one', 'One', 'two'), 'one') [==] array('one', 'One').
	 *
	 * @covers Kotchasan\ArrayTool::filter
	 */
	public function testFilter()
	{

		$this->assertEquals(
			array('one', 'One'), \Kotchasan\ArrayTool::filter(array('one', 'One', 'two'), 'one')
		);
	}

	/**
	 * Generated from @assert ('|', array('a' => 'A', 'b' => array('b', 'B'), 'c' => array('c' => array('c', 'C')))) [==] "A|b|B|c|C".
	 *
	 * @covers Kotchasan\ArrayTool::toString
	 */
	public function testToString()
	{

		$this->assertEquals(
			"A|b|B|c|C", \Kotchasan\ArrayTool::toString('|', array('a' => 'A', 'b' => array('b', 'B'), 'c' => array('c' => array('c', 'C'))))
		);
	}

	/**
	 * Generated from @assert (array(0, 1, 2, 3, 4, 5), '0,2') [==] array(1, 3, 4, 5).
	 *
	 * @covers Kotchasan\ArrayTool::delete
	 */
	public function testDelete()
	{

		$this->assertEquals(
			array(1, 3, 4, 5), \Kotchasan\ArrayTool::delete(array(0, 1, 2, 3, 4, 5), '0,2')
		);
	}

	/**
	 * Generated from @assert (array(1 => 1, 2 => 2, 3 => 'three'), array(1 => 'one', 2 => 'two')) [==] array(1 => 'one', 2 => 'two', 3 => 'three').
	 *
	 * @covers Kotchasan\ArrayTool::replace
	 */
	public function testReplace()
	{

		$this->assertEquals(
			array(1 => 'one', 2 => 'two', 3 => 'three'), \Kotchasan\ArrayTool::replace(array(1 => 1, 2 => 2, 3 => 'three'), array(1 => 'one', 2 => 'two'))
		);
	}

	/**
	 * Generated from @assert (array(1 => 1, 2 => 2, 3 => 'three'), array(1 => 'one', 2 => 'two')) [==] array(1 => 'one', 2 => 'two', 3 => 'three').
	 *
	 * @covers Kotchasan\ArrayTool::merge
	 */
	public function testMerge()
	{

		$this->assertEquals(
			array(1 => 'one', 2 => 'two', 3 => 'three'), \Kotchasan\ArrayTool::merge(array(1 => 1, 2 => 2, 3 => 'three'), array(1 => 'one', 2 => 'two'))
		);
	}

	/**
	 * Generated from @assert ('') [==] array().
	 *
	 * @covers Kotchasan\ArrayTool::unserialize
	 */
	public function testUnserialize()
	{

		$this->assertEquals(
			array(), \Kotchasan\ArrayTool::unserialize('')
		);
	}

	/**
	 * Generated from @assert (serialize(array(1, 2, 3))) [==] array(1, 2, 3).
	 *
	 * @covers Kotchasan\ArrayTool::unserialize
	 */
	public function testUnserialize2()
	{

		$this->assertEquals(
			array(1, 2, 3), \Kotchasan\ArrayTool::unserialize(serialize(array(1, 2, 3)))
		);
	}

	/**
	 * Generated from @assert (serialize(array(1 => 'One', 2 => 'Two', 3 => 'Three')), array(3 => 3, 4 => 'Four'), true) [==] array(1 => 'One', 2 => 'Two', 3 => 'Three', 4 => 'Four').
	 *
	 * @covers Kotchasan\ArrayTool::unserialize
	 */
	public function testUnserialize3()
	{

		$this->assertEquals(
			array(1 => 'One', 2 => 'Two', 3 => 'Three', 4 => 'Four'), \Kotchasan\ArrayTool::unserialize(serialize(array(1 => 'One', 2 => 'Two', 3 => 'Three')), array(3 => 3, 4 => 'Four'), true)
		);
	}

	/**
	 * Generated from @assert (serialize(array(1 => 'One', 2 => 'Two', 3 => 'Three')), array(3 => 3, 4 => 'Four'), false) [==] array(1 => 'One', 2 => 'Two', 3 => 3, 4 => 'Four').
	 *
	 * @covers Kotchasan\ArrayTool::unserialize
	 */
	public function testUnserialize4()
	{

		$this->assertEquals(
			array(1 => 'One', 2 => 'Two', 3 => 3, 4 => 'Four'), \Kotchasan\ArrayTool::unserialize(serialize(array(1 => 'One', 2 => 'Two', 3 => 'Three')), array(3 => 3, 4 => 'Four'), false)
		);
	}

	/**
	 * @covers Kotchasan\ArrayTool::extract
	 * @todo   Implement testExtract().
	 */
	public function testExtract()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}