<?php

namespace Kotchasan;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-19 at 13:43:27.
 */
class ViewTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var View
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{

	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{

	}

	/**
	 * Generated from @assert (array(2 => 'module=retmodule')) [==] "http://localhost/?module=retmodule&amp;page=1&amp;sort=id"  [[$_SERVER['QUERY_STRING'] = '_module=test&_page=1&_sort=id']].
	 *
	 * @covers Kotchasan\View::back
	 */
	public function testBack()
	{
		$_SERVER['QUERY_STRING'] = '_module=test&_page=1&_sort=id';
		$this->assertEquals(
		"http://localhost/?module=retmodule&amp;page=1&amp;sort=id", \Kotchasan\View::back(array(2 => 'module=retmodule'))
		);
	}

	/**
	 * Generated from @assert ('module=retmodule') [==] "http://localhost/?module=retmodule&amp;page=1&amp;sort=id" [[$_SERVER['QUERY_STRING'] = '_module=test&_page=1&_sort=id']].
	 *
	 * @covers Kotchasan\View::back
	 */
	public function testBack2()
	{
		$_SERVER['QUERY_STRING'] = '_module=test&_page=1&_sort=id';
		$this->assertEquals(
		"http://localhost/?module=retmodule&amp;page=1&amp;sort=id", \Kotchasan\View::back('module=retmodule')
		);
	}

	/**
	 * @covers Kotchasan\View::setContents
	 * @todo   Implement testSetContents().
	 */
	public function testSetContents()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Kotchasan\View::setMetas
	 * @todo   Implement testSetMetas().
	 */
	public function testSetMetas()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Kotchasan\View::setHeaders
	 * @todo   Implement testSetHeaders().
	 */
	public function testSetHeaders()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Kotchasan\View::renderHTML
	 * @todo   Implement testRenderHTML().
	 */
	public function testRenderHTML()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Kotchasan\View::output
	 * @todo   Implement testOutput().
	 */
	public function testOutput()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		'This test has not been implemented yet.'
		);
	}
}